### ISSUE TITLE
[15.0] RPC_Error Keycloak Addons

### ISSUE THREAD

**Issue by Entrepreneur-AJ** [Mint-System/Odoo-Apps-Server-Tools#2]
On a fresh install to test the module before prod deployment, I get the following error;

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/core/odoo/tools/convert.py", line 683, in _tag_root
    f(rec)
  File "/home/odoo/core/odoo/tools/convert.py", line 586, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/core/odoo/models.py", line 4431, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/core/odoo/models.py", line 4347, in _load_records_create
    return self.create(values)
  File "<decorator-gen-42>", line 2, in create
  File "/home/odoo/core/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/core/odoo/addons/base/models/ir_ui_view.py", line 546, in create
    result = super(View, self.with_context(ir_ui_view_partial_validation=True)).create(vals_list)
  File "<decorator-gen-67>", line 2, in create
  File "/home/odoo/core/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/core/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/odoo/core/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/core/odoo/models.py", line 4079, in create
    records = self._create(data_list)
  File "/home/odoo/core/odoo/models.py", line 4244, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/home/odoo/core/odoo/models.py", line 1367, in _validate_fields
    check(self)
  File "/home/odoo/core/odoo/addons/base/models/ir_ui_view.py", line 467, in _check_xml
    raise err.with_traceback(e.__traceback__) from None
  File "/home/odoo/core/odoo/addons/base/models/ir_ui_view.py", line 441, in _check_xml
    view._validate_view(combined_arch, view.model)
  File "/home/odoo/core/odoo/addons/base/models/ir_ui_view.py", line 1299, in _validate_view
    validator(node, name_manager, node_info)
  File "/home/odoo/core/odoo/addons/base/models/ir_ui_view.py", line 1408, in _validate_tag_field
    self._raise_view_error(msg, node)
  File "/home/odoo/core/odoo/addons/base/models/ir_ui_view.py", line 746, in _raise_view_error
    raise err from from_exception
odoo.exceptions.ValidationError: Error while validating view near:

                    <sheet>
                        <group>
                            <field name="name"/>
                            <field name="client_id"/>
                            <field name="enabled"/>

Field "x_keycloak" does not exist in model "auth.oauth.provider"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/core/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/core/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/core/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/core/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/core/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/core/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/core/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/core/addons/web/controllers/main.py", line 1346, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/core/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/core/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/core/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/home/odoo/core/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/core/odoo/addons/base/models/ir_module.py", line 486, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/core/odoo/addons/base/models/ir_module.py", line 603, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/core/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/core/odoo/modules/loading.py", line 474, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/core/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/core/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/core/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/core/odoo/tools/convert.py", line 748, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/core/odoo/tools/convert.py", line 814, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/core/odoo/tools/convert.py", line 734, in parse
    self._tag_root(de)
  File "/home/odoo/core/odoo/tools/convert.py", line 694, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/core/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/core/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /home/odoo/addons/auth_oauth_keycloak/views/auth_oauth.xml:3
Error while validating view near:

                    <sheet>
                        <group>
                            <field name="name"/>
                            <field name="client_id"/>
                            <field name="enabled"/>

Field "x_keycloak" does not exist in model "auth.oauth.provider"

View error context:
{'file': '/home/odoo/addons/auth_oauth_keycloak/views/auth_oauth.xml',
 'line': 4,
 'name': 'auth_oauth_keycloak.view_oauth_provider_form',
 'view': ir.ui.view(379,),
 'view.model': 'auth.oauth.provider',
 'view.parent': ir.ui.view(341,),
 'xmlid': 'view_oauth_provider_form'}

**Comment by jonahbohlmann** [comment]
Hi,

I have the same issue. Any solution?

**Comment by jonahbohlmann** [comment]
FYI: as a workaround, I created the field x_keycloak manually via Settings -> data models -> auth.oauth.provider model

Then I added the field as boolean. After that, the installation finished with success and I was able to use keycloak.
